version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  # Dependencies listed in go.mod
  - package-ecosystem: "gomod"
    # Location of package manifests
    directory: "/"
    schedule:
      interval: "weekly"
