version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"  # Dependencies listed in go.mod
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
