version: "2"
linters:
  enable:
    - errorlint
    - gocritic
    - gosec
    - misspell
    - nonamedreturns
    - unconvert
    - unparam
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/vishvananda)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
